services:
  qnetd:
    container_name: proxmox-qdevice
    image: bcleonard/proxmox-qdevice:v2.0
    ports:
      - "22:22"
      - "5403:5403"
    environment:
      - NEW_ROOT_PASSWORD=${NEW_ROOT_PASSWORD}
      - PUID=996
      - PGID=988
      - TZ=America/New_York
    volumes:
      - /mnt/data/docker/volumes/corosync:/etc/corosync:rw
      - /mnt/data/docker/volumes/corosync_logs:/var/log/corosync:rw
    restart: unless-stopped
    hostname: qdevice.kitzy.net
    networks: 
      vlan:
        ipv4_address: 10.253.20.98

networks:
 vlan:
    driver: macvlan
    driver_opts:
      parent: bond0
    ipam:
       driver: default
       config:
        - subnet: "10.253.20.0/24"
          ip_range: "10.253.20.98/32"
          gateway: "10.253.20.1"
